apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_DB: dGVzdGRhdGFiYXNl
  POSTGRES_USER: dGVzdHVzZXI=
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXk=
