---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redmine
  labels:
    app: app-redmine
  namespace: postgres
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-redmine
  template:
    metadata:
      labels:
        app: app-redmine
    spec:
      hostNetwork: true
      containers:
      - image: redmine:4.1.1
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USER
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          - name: REDMINE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_DB
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: REDMINE_SECRET_KEY_BASE
        name: redmine
        ports:
          - containerPort: 3000

        
