---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redmine-ingress
  namespace: postgres
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: redmine.local
    http:
      paths: /
      pathType: Prefix
      - backend:
          serviceName: redmine-service
          servicePort: 8080
